apiVersion: batch/v1
kind: Job
metadata:
  name: part3-blackscholes
  labels:
    name: part3-blackscholes
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_blackscholes
        name: part3-blackscholes
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0,1 ./run -a run -S parsec -p blackscholes -i native -n 2"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
