apiVersion: batch/v1
kind: Job
metadata:
  name: part3-dedup
  labels:
    name: part3-dedup
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_dedup
        name: part3-dedup
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 1 ./run -a run -S parsec -p dedup -i native -n 1"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
