apiVersion: batch/v1
kind: Job
metadata:
  name: part3-ferret
  labels:
    name: part3-ferret
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_ferret
        name: part3-ferret
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0,1,2,3 ./run -a run -S parsec -p ferret -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
