apiVersion: batch/v1
kind: Job
metadata:
  name: part3-freqmine
  labels:
    name: part3-freqmine
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_freqmine
        name: part3-freqmine
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 4,5,6,7 ./run -a run -S parsec -p freqmine -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
