apiVersion: v1
kind: Pod
metadata:
  name: part3-memcached
  labels:
    name: part3-memcached
spec:
  containers:
    - image: anakli/memcached:t1
      name: part3-memcached
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args: ["-c", "./memcached -t 2 -u memcache"]
  nodeSelector:
    cca-project-nodetype: "node-a-2core"
